#ifndef _ViewC64AllGraphicsDefs_h_
#define _ViewC64AllGraphicsDefs_h_

#define VIEW_C64_ALL_GRAPHICS_MODE_BITMAPS      1
#define VIEW_C64_ALL_GRAPHICS_MODE_SCREENS      2
#define VIEW_C64_ALL_GRAPHICS_MODE_CHARSETS     3
#define VIEW_C64_ALL_GRAPHICS_MODE_SPRITES      4
#define VIEW_C64_ALL_GRAPHICS_MODE_COLOR        5

#define VIEW_C64_ALL_GRAPHICS_FORCED_NONE       0
#define VIEW_C64_ALL_GRAPHICS_FORCED_GRAY       1
#define VIEW_C64_ALL_GRAPHICS_FORCED_HIRES      2
#define VIEW_C64_ALL_GRAPHICS_FORCED_MULTI      3

#endif
