/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gtyyrestart( gtyyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int gtyyleng;
extern FILE *gtyyin, *gtyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtyytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gtyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, gtyytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gtyyrestart()), so that the user can continue scanning by
	 * just pointing gtyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when gtyytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int gtyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh gtyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;


void gtyyrestart YY_PROTO(( FILE *input_file ));

void gtyy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void gtyy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE gtyy_create_buffer YY_PROTO(( FILE *file, int size ));
void gtyy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void gtyy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void gtyy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER gtyy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE gtyy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE gtyy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE gtyy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *gtyy_flex_alloc YY_PROTO(( yy_size_t ));
static void *gtyy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void gtyy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer gtyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = gtyy_create_buffer( gtyyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = gtyy_create_buffer( gtyyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *gtyyin = (FILE *) 0, *gtyyout = (FILE *) 0;
typedef int yy_state_type;
extern char *gtyytext;
#define gtyytext_ptr gtyytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gtyytext.
 */
#define YY_DO_BEFORE_ACTION \
	gtyytext_ptr = yy_bp; \
	gtyyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
static yyconst short int yy_accept[256] =
    {   0,
        0,    0,    0,    0,    0,    0,  107,  107,    0,    0,
        0,    0,  112,   93,   92,   91,   93,   74,   16,   81,
       93,   86,   93,   77,   78,   84,   82,   79,   83,   93,
       85,   68,   80,   17,   70,   87,   71,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   88,   89,   93,   99,   98,   99,   99,  106,
      105,  106,  106,  107,  107,  107,  109,  111,  110,  111,
      102,  101,   91,   73,   69,   75,    0,    0,    0,    0,
        0,    0,    0,    0,   68,   72,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   76,
       98,    0,    0,  105,    0,    0,  107,  107,  110,  102,
      101,    0,    0,    0,    0,    0,    0,    0,    1,    0,
        0,    0,    0,    0,   27,   24,   65,   52,   53,   50,
       55,   51,   54,   56,   57,   45,   39,   29,   30,   31,
       63,   59,   61,   26,   62,   58,   60,   49,   48,   18,
       19,   20,   64,   40,   25,   34,   36,   35,   37,   67,
       66,   47,   28,   46,   38,   21,   22,   23,   44,   42,
       32,   43,   33,   41,    0,    0,   94,    0,  103,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
       13,    0,    0,    0,    0,    0,    0,   15,    0,   10,
        2,    3,    0,    0,    0,    0,    0,    0,   14,   95,
       96,    0,    0,    0,    0,    4,    9,    0,    0,    0,
        6,   97,  104,    0,    0,   11,    0,    0,    0,    7,
        5,   12,    0,  100,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   36,
        1,    1,    1,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   36,    1,   51,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    1,
        1,    1,    1,    1,    5,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1
    } ;

static yyconst short int yy_base[265] =
    {   0,
        0,    0,   49,   51,   53,   55,   57,   61,   70,   72,
      275,  274,  290,  293,  293,  293,  286,  265,  293,  293,
        0,  293,  277,  293,  293,  293,  293,  293,  293,   50,
      293,  267,  293,  293,  293,  262,  293,   42,   61,   66,
      254,  243,    0,  243,   57,   53,  241,  237,   50,   65,
       79,   68,    0,    0,  228,  293,  293,  275,   62,  293,
      293,  274,   81,    0,    0,  273,  293,  293,  293,  272,
        0,   96,  293,  293,    0,  293,  224,  243,   86,   88,
      246,  228,  240,  229,  249,  293,    0,  239,  237,  228,
       34,  222,  229,  232,  224,   41,   88,  219,   71,  100,

      216,  102,  217,  214,  105,  213,  214,  228,  106,  107,
       97,  209,  224,  107,  110,   88,  202,  113,  224,  293,
      293,  105,  218,  293,  209,  216,    0,    0,  293,    0,
      229,  206,  199,  212,  209,  109,  212,  197,  293,  211,
      210,  205,  192,  192,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  112,  205,  293,  204,  293,  203,

      201,  196,  189,  197,  197,  192,  185,  131,  181,  293,
      293,  194,  191,  191,  186,  185,  180,  293,  178,  293,
      293,  293,  183,  165,  144,  131,  136,  135,  293,  293,
      293,  143,  142,  146,  141,  293,  293,  131,  140,  124,
      293,  293,  293,  138,  136,  293,  134,  134,  119,  293,
      293,  293,  121,  293,  293,  179,  184,  189,  194,  199,
      141,  201,  206,  211
    } ;

static yyconst short int yy_def[265] =
    {   0,
      255,    1,  256,  256,  257,  257,  258,  258,  259,  259,
      260,  260,  255,  255,  255,  255,  255,  255,  255,  255,
      261,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  263,  263,  263,  255,  255,  255,  255,
      264,  255,  255,  255,  261,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  255,
      255,  255,  255,  255,  255,  255,  263,  263,  255,  264,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,    0,  255,  255,  255,  255,  255,
      255,  255,  255,  255
    } ;

static yyconst short int yy_nxt[345] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   14,   38,   39,   40,   41,   42,
       43,   43,   43,   44,   45,   43,   46,   43,   47,   48,
       49,   43,   50,   51,   52,   43,   43,   43,   53,   54,
       55,   57,   58,   57,   58,   61,   62,   61,   62,   65,
       66,  148,   67,   65,   66,   59,   67,   59,  154,   63,
       88,   63,   69,   70,   69,   70,   77,  149,   78,   79,
       89,  105,  109,   80,  155,   90,  110,   81,   91,   82,
       92,  122,   83,  116,  103,  123,  106,   84,   93,   94,

      104,   95,   97,   98,  111,  113,   99,   96,  114,  112,
      125,  117,  131,  135,  126,  156,  118,  119,  139,  159,
      160,  157,  136,  115,  137,  132,  140,  161,  138,  165,
      170,  176,  178,  180,  184,  186,  189,  190,  192,  181,
      185,  195,  204,  196,   75,  213,  177,  179,  162,  163,
      166,  167,  205,  171,  172,  214,  193,  225,  187,  188,
      254,  253,  252,  251,  250,  249,  248,  226,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  227,   56,
       56,   56,   56,   56,   60,   60,   60,   60,   60,   64,
       64,   64,   64,   64,   68,   68,   68,   68,   68,   71,

       71,   71,   71,   71,   87,   87,  127,  237,  127,  127,
      127,  130,  130,  236,  130,  130,  235,  234,  233,  232,
      231,  230,  229,  228,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  212,  211,  210,  209,  208,  207,
      206,  203,  202,  201,  200,  131,  199,  198,  197,  194,
      191,  183,  182,  175,  174,  173,  169,  168,  164,  158,
      153,  152,  151,  150,  147,  146,  145,   85,  144,  143,
      142,  141,  134,  133,  129,  128,  124,  121,  120,  108,
      107,  102,  101,  100,   86,   85,   76,   74,   73,  255,
       72,   72,   13,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255
    } ;

static yyconst short int yy_chk[345] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    5,    5,    6,    6,    7,
        7,   91,    7,    8,    8,    3,    8,    4,   96,    5,
       38,    6,    9,    9,   10,   10,   30,   91,   30,   30,
       38,   46,   49,   30,   96,   38,   49,   30,   39,   30,
       39,   59,   30,   52,   45,   59,   46,   30,   39,   39,

       45,   39,   40,   40,   50,   51,   40,   39,   51,   50,
       63,   52,   72,   79,   63,   97,   52,   52,   80,   99,
       99,   97,   79,   51,   79,   72,   80,  100,   79,  102,
      105,  109,  110,  111,  114,  115,  116,  116,  118,  111,
      114,  122,  136,  122,  261,  195,  109,  110,  100,  100,
      102,  102,  136,  105,  105,  195,  118,  208,  115,  115,
      253,  249,  248,  247,  245,  244,  240,  208,  239,  238,
      235,  234,  233,  232,  228,  227,  226,  225,  208,  256,
      256,  256,  256,  256,  257,  257,  257,  257,  257,  258,
      258,  258,  258,  258,  259,  259,  259,  259,  259,  260,

      260,  260,  260,  260,  262,  262,  263,  224,  263,  263,
      263,  264,  264,  223,  264,  264,  219,  217,  216,  215,
      214,  213,  212,  209,  207,  206,  205,  204,  203,  202,
      201,  200,  198,  196,  144,  143,  142,  141,  140,  138,
      137,  135,  134,  133,  132,  131,  126,  125,  123,  119,
      117,  113,  112,  108,  107,  106,  104,  103,  101,   98,
       95,   94,   93,   92,   90,   89,   88,   85,   84,   83,
       82,   81,   78,   77,   70,   66,   62,   58,   55,   48,
       47,   44,   42,   41,   36,   32,   23,   18,   17,   13,
       12,   11,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *gtyytext;
// #line 1 "asm.yy"
#define INITIAL 0
/* scanner for a simple assembler */
// #line 3 "asm.yy"
#include <stdio.h>
#include <string.h>
#include "gt-int.h"
#include "gt-membuf.h"
#include "gt-parse.h"
#include "gt-asmtab.h"



#define MAX_SRC_BUFFER_DEPTH 10
static YY_BUFFER_STATE src_buffers[MAX_SRC_BUFFER_DEPTH];
static int src_buffer_depth = 0;

static char *strdupped_get(char *text);
static int strdupped_cmp(const void *a, const void *b);
static void strdupped_free(void *a);

int num_lines = 1;
int push_state_skip = 0;
int push_state_init = 0;
int push_state_macro = 0;
struct vec strdupped[1];

#define SKIP 1
#define SKIP_ALL 2
#define QUOTED_STRING 3
#define SKIP_LINE 4
#define MACROO 5

#define YY_STACK_USED 1
// #line 558 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef gtyytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int gtyyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( gtyytext, gtyyleng, 1, gtyyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gtyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gtyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, gtyyin )) == 0) \
		  && ferror( gtyyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int gtyylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after gtyytext and gtyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

// #line 32 "asm.yy"


	if(push_state_init)
	{push_state_init = 0; yy_push_state(INITIAL); }
	if(push_state_skip)
	{push_state_skip = 0; yy_push_state(SKIP); }
	if(push_state_macro)
	{push_state_macro = 0; yy_push_state(MACROO); }

// #line 719 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! gtyyin )
			gtyyin = stdin;

		if ( ! gtyyout )
			gtyyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				gtyy_create_buffer( gtyyin, YY_BUF_SIZE );

		gtyy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of gtyytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 256 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 255 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
// #line 41 "asm.yy"
return IF;
	YY_BREAK
case 2:
YY_RULE_SETUP
// #line 42 "asm.yy"
BEGIN(SKIP_ALL);
	YY_BREAK
case 3:
YY_RULE_SETUP
// #line 43 "asm.yy"
BEGIN(SKIP);
	YY_BREAK
case 4:
YY_RULE_SETUP
// #line 44 "asm.yy"
yy_pop_state();
	YY_BREAK
case 5:
YY_RULE_SETUP
// #line 46 "asm.yy"
return INCLUDE;
	YY_BREAK
case 6:
YY_RULE_SETUP
// #line 47 "asm.yy"
return MACRO;
	YY_BREAK
case 7:
YY_RULE_SETUP
// #line 49 "asm.yy"
return DEFINED;
	YY_BREAK
case 8:
YY_RULE_SETUP
// #line 50 "asm.yy"
return ORG;
	YY_BREAK
case 9:
YY_RULE_SETUP
// #line 51 "asm.yy"
return ASMERROR;
	YY_BREAK
case 10:
YY_RULE_SETUP
// #line 52 "asm.yy"
return ECHO;
	YY_BREAK
case 11:
YY_RULE_SETUP
// #line 53 "asm.yy"
return INCBIN;
	YY_BREAK
case 12:
YY_RULE_SETUP
// #line 54 "asm.yy"
return INCWORD;
	YY_BREAK
case 13:
YY_RULE_SETUP
// #line 55 "asm.yy"
return RES;
	YY_BREAK
case 14:
YY_RULE_SETUP
// #line 56 "asm.yy"
return WORD;
	YY_BREAK
case 15:
YY_RULE_SETUP
// #line 57 "asm.yy"
return BYTE;
	YY_BREAK
case 16:
YY_RULE_SETUP
// #line 59 "asm.yy"
BEGIN(QUOTED_STRING);
	YY_BREAK
case 17:
YY_RULE_SETUP
// #line 60 "asm.yy"
BEGIN(SKIP_LINE);
	YY_BREAK
case 18:
YY_RULE_SETUP
// #line 62 "asm.yy"
return LDA;
	YY_BREAK
case 19:
YY_RULE_SETUP
// #line 63 "asm.yy"
return LDX;
	YY_BREAK
case 20:
YY_RULE_SETUP
// #line 64 "asm.yy"
return LDY;
	YY_BREAK
case 21:
YY_RULE_SETUP
// #line 65 "asm.yy"
return STA;
	YY_BREAK
case 22:
YY_RULE_SETUP
// #line 66 "asm.yy"
return STX;
	YY_BREAK
case 23:
YY_RULE_SETUP
// #line 67 "asm.yy"
return STY;
	YY_BREAK
case 24:
YY_RULE_SETUP
// #line 68 "asm.yy"
return AND;
	YY_BREAK
case 25:
YY_RULE_SETUP
// #line 69 "asm.yy"
return ORA;
	YY_BREAK
case 26:
YY_RULE_SETUP
// #line 70 "asm.yy"
return EOR;
	YY_BREAK
case 27:
YY_RULE_SETUP
// #line 71 "asm.yy"
return ADC;
	YY_BREAK
case 28:
YY_RULE_SETUP
// #line 72 "asm.yy"
return SBC;
	YY_BREAK
case 29:
YY_RULE_SETUP
// #line 73 "asm.yy"
return CMP;
	YY_BREAK
case 30:
YY_RULE_SETUP
// #line 74 "asm.yy"
return CPX;
	YY_BREAK
case 31:
YY_RULE_SETUP
// #line 75 "asm.yy"
return CPY;
	YY_BREAK
case 32:
YY_RULE_SETUP
// #line 77 "asm.yy"
return TSX;
	YY_BREAK
case 33:
YY_RULE_SETUP
// #line 78 "asm.yy"
return TXS;
	YY_BREAK
case 34:
YY_RULE_SETUP
// #line 79 "asm.yy"
return PHA;
	YY_BREAK
case 35:
YY_RULE_SETUP
// #line 80 "asm.yy"
return PLA;
	YY_BREAK
case 36:
YY_RULE_SETUP
// #line 81 "asm.yy"
return PHP;
	YY_BREAK
case 37:
YY_RULE_SETUP
// #line 82 "asm.yy"
return PLP;
	YY_BREAK
case 38:
YY_RULE_SETUP
// #line 83 "asm.yy"
return SEI;
	YY_BREAK
case 39:
YY_RULE_SETUP
// #line 84 "asm.yy"
return CLI;
	YY_BREAK
case 40:
YY_RULE_SETUP
// #line 85 "asm.yy"
return NOP;
	YY_BREAK
case 41:
YY_RULE_SETUP
// #line 86 "asm.yy"
return TYA;
	YY_BREAK
case 42:
YY_RULE_SETUP
// #line 87 "asm.yy"
return TAY;
	YY_BREAK
case 43:
YY_RULE_SETUP
// #line 88 "asm.yy"
return TXA;
	YY_BREAK
case 44:
YY_RULE_SETUP
// #line 89 "asm.yy"
return TAX;
	YY_BREAK
case 45:
YY_RULE_SETUP
// #line 90 "asm.yy"
return CLC;
	YY_BREAK
case 46:
YY_RULE_SETUP
// #line 91 "asm.yy"
return SEC;
	YY_BREAK
case 47:
YY_RULE_SETUP
// #line 92 "asm.yy"
return RTS;
	YY_BREAK
case 48:
YY_RULE_SETUP
// #line 94 "asm.yy"
return JSR;
	YY_BREAK
case 49:
YY_RULE_SETUP
// #line 95 "asm.yy"
return JMP;
	YY_BREAK
case 50:
YY_RULE_SETUP
// #line 96 "asm.yy"
return BEQ;
	YY_BREAK
case 51:
YY_RULE_SETUP
// #line 97 "asm.yy"
return BNE;
	YY_BREAK
case 52:
YY_RULE_SETUP
// #line 98 "asm.yy"
return BCC;
	YY_BREAK
case 53:
YY_RULE_SETUP
// #line 99 "asm.yy"
return BCS;
	YY_BREAK
case 54:
YY_RULE_SETUP
// #line 100 "asm.yy"
return BPL;
	YY_BREAK
case 55:
YY_RULE_SETUP
// #line 101 "asm.yy"
return BMI;
	YY_BREAK
case 56:
YY_RULE_SETUP
// #line 102 "asm.yy"
return BVC;
	YY_BREAK
case 57:
YY_RULE_SETUP
// #line 103 "asm.yy"
return BCS;
	YY_BREAK
case 58:
YY_RULE_SETUP
// #line 104 "asm.yy"
return INX;
	YY_BREAK
case 59:
YY_RULE_SETUP
// #line 105 "asm.yy"
return DEX;
	YY_BREAK
case 60:
YY_RULE_SETUP
// #line 106 "asm.yy"
return INY;
	YY_BREAK
case 61:
YY_RULE_SETUP
// #line 107 "asm.yy"
return DEY;
	YY_BREAK
case 62:
YY_RULE_SETUP
// #line 108 "asm.yy"
return INC;
	YY_BREAK
case 63:
YY_RULE_SETUP
// #line 109 "asm.yy"
return DEC;
	YY_BREAK
case 64:
YY_RULE_SETUP
// #line 110 "asm.yy"
return LSR;
	YY_BREAK
case 65:
YY_RULE_SETUP
// #line 111 "asm.yy"
return ASL;
	YY_BREAK
case 66:
YY_RULE_SETUP
// #line 112 "asm.yy"
return ROR;
	YY_BREAK
case 67:
YY_RULE_SETUP
// #line 113 "asm.yy"
return ROL;
	YY_BREAK
case 68:
YY_RULE_SETUP
// #line 115 "asm.yy"
{ yylval.num = atoi(gtyytext); return NUMBER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
// #line 117 "asm.yy"
{ yylval.num = strtol(gtyytext + 1, NULL, 16); return NUMBER; }
	YY_BREAK
case 70:
YY_RULE_SETUP
// #line 119 "asm.yy"
return LT;
	YY_BREAK
case 71:
YY_RULE_SETUP
// #line 120 "asm.yy"
return GT;
	YY_BREAK
case 72:
YY_RULE_SETUP
// #line 121 "asm.yy"
return EQ;
	YY_BREAK
case 73:
YY_RULE_SETUP
// #line 122 "asm.yy"
return NEQ;
	YY_BREAK
case 74:
YY_RULE_SETUP
// #line 123 "asm.yy"
return LNOT;
	YY_BREAK
case 75:
YY_RULE_SETUP
// #line 124 "asm.yy"
return LAND;
	YY_BREAK
case 76:
YY_RULE_SETUP
// #line 125 "asm.yy"
return LOR;
	YY_BREAK
case 77:
YY_RULE_SETUP
// #line 127 "asm.yy"
return LPAREN;
	YY_BREAK
case 78:
YY_RULE_SETUP
// #line 128 "asm.yy"
return RPAREN;
	YY_BREAK
case 79:
YY_RULE_SETUP
// #line 129 "asm.yy"
return COMMA;
	YY_BREAK
case 80:
YY_RULE_SETUP
// #line 130 "asm.yy"
return COLON;
	YY_BREAK
case 81:
YY_RULE_SETUP
// #line 131 "asm.yy"
return HASH;
	YY_BREAK
case 82:
YY_RULE_SETUP
// #line 132 "asm.yy"
return PLUS;
	YY_BREAK
case 83:
YY_RULE_SETUP
// #line 133 "asm.yy"
return MINUS;
	YY_BREAK
case 84:
YY_RULE_SETUP
// #line 134 "asm.yy"
return MULT;
	YY_BREAK
case 85:
YY_RULE_SETUP
// #line 135 "asm.yy"
return DIV;
	YY_BREAK
case 86:
YY_RULE_SETUP
// #line 136 "asm.yy"
return MOD;
	YY_BREAK
case 87:
YY_RULE_SETUP
// #line 138 "asm.yy"
return ASSIGN;
	YY_BREAK
case 88:
YY_RULE_SETUP
// #line 140 "asm.yy"
return X;
	YY_BREAK
case 89:
YY_RULE_SETUP
// #line 141 "asm.yy"
return Y;
	YY_BREAK
case 90:
YY_RULE_SETUP
// #line 143 "asm.yy"
{ yylval.str = strdupped_get(gtyytext); return SYMBOL; }
	YY_BREAK
case 91:
YY_RULE_SETUP
// #line 145 "asm.yy"
++num_lines;
	YY_BREAK
case 92:
YY_RULE_SETUP
// #line 147 "asm.yy"
/* eat whitespace */
	YY_BREAK
case 93:
YY_RULE_SETUP
// #line 149 "asm.yy"
printf("unknown character found %s\n", gtyytext);
	YY_BREAK
case 94:
YY_RULE_SETUP
// #line 151 "asm.yy"
yy_push_state(SKIP_ALL);
	YY_BREAK
case 95:
YY_RULE_SETUP
// #line 152 "asm.yy"
{ yy_pop_state(); return IF; }
	YY_BREAK
case 96:
YY_RULE_SETUP
// #line 153 "asm.yy"
BEGIN(INITIAL);
	YY_BREAK
case 97:
YY_RULE_SETUP
// #line 154 "asm.yy"
yy_pop_state();
	YY_BREAK
case 98:
YY_RULE_SETUP
// #line 155 "asm.yy"
++num_lines;
	YY_BREAK
case 99:
YY_RULE_SETUP
// #line 156 "asm.yy"

	YY_BREAK
case 100:
YY_RULE_SETUP
// #line 158 "asm.yy"
yy_pop_state();
	YY_BREAK
case 101:
YY_RULE_SETUP
// #line 159 "asm.yy"
{ yylval.str = gtyytext; return MACRO_STRING; }
	YY_BREAK
case 102:
YY_RULE_SETUP
// #line 160 "asm.yy"
{ yylval.str = gtyytext; return MACRO_STRING; }
	YY_BREAK
case 103:
YY_RULE_SETUP
// #line 162 "asm.yy"
yy_push_state(SKIP_ALL);
	YY_BREAK
case 104:
YY_RULE_SETUP
// #line 163 "asm.yy"
yy_pop_state();
	YY_BREAK
case 105:
YY_RULE_SETUP
// #line 164 "asm.yy"
++num_lines;
	YY_BREAK
case 106:
YY_RULE_SETUP
// #line 165 "asm.yy"

	YY_BREAK
case 107:
YY_RULE_SETUP
// #line 167 "asm.yy"
{
    yylval.str = strdupped_get(gtyytext);
    return STRING;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
// #line 171 "asm.yy"
++num_lines;
	YY_BREAK
case 109:
YY_RULE_SETUP
// #line 172 "asm.yy"
BEGIN(INITIAL);
	YY_BREAK
case 110:
YY_RULE_SETUP
// #line 174 "asm.yy"
{ ++num_lines; BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SKIP):
case YY_STATE_EOF(SKIP_ALL):
case YY_STATE_EOF(QUOTED_STRING):
case YY_STATE_EOF(SKIP_LINE):
case YY_STATE_EOF(MACROO):
// #line 176 "asm.yy"
{
	    if(--src_buffer_depth == 0)
	    {
	    	yyterminate();
	    }
	    else
	    {
		gtyy_delete_buffer(YY_CURRENT_BUFFER);
		gtyy_switch_to_buffer(src_buffers[src_buffer_depth]);
	    }
	}
	YY_BREAK
case 111:
YY_RULE_SETUP
// #line 188 "asm.yy"
ECHO;
	YY_BREAK
// #line 1375 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - gtyytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gtyyin at a new source and called
			 * gtyylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = gtyyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = gtyytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = gtyytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gtyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = gtyytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					gtyytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = gtyytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = gtyytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of gtyylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = gtyytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - gtyytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - gtyytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					gtyy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gtyyrestart( gtyyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	gtyytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = gtyytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 256 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 256 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 255);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up gtyytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	gtyytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int gtyyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - gtyytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gtyyrestart( gtyyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return gtyyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = gtyytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve gtyytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void gtyyrestart( FILE *input_file )
#else
void gtyyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = gtyy_create_buffer( gtyyin, YY_BUF_SIZE );

	gtyy_init_buffer( yy_current_buffer, input_file );
	gtyy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void gtyy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void gtyy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	gtyy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void gtyy_load_buffer_state( void )
#else
void gtyy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	gtyytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	gtyyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE gtyy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE gtyy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) gtyy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtyy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gtyy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	gtyy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void gtyy_delete_buffer( YY_BUFFER_STATE b )
#else
void gtyy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{

	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gtyy_flex_free( (void *) b->yy_ch_buf );

	gtyy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void gtyy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void gtyy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	gtyy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void gtyy_flush_buffer( YY_BUFFER_STATE b )
#else
void gtyy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		gtyy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE gtyy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE gtyy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gtyy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gtyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gtyy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE gtyy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE gtyy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return gtyy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE gtyy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE gtyy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) gtyy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gtyy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = gtyy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gtyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) gtyy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) gtyy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gtyytext. */ \
		gtyytext[gtyyleng] = yy_hold_char; \
		yy_c_buf_p = gtyytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		gtyyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef gtyytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *gtyy_flex_alloc( yy_size_t size )
#else
static void *gtyy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *gtyy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *gtyy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void gtyy_flex_free( void *ptr )
#else
static void gtyy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	gtyylex();
	return 0;
	}
#endif
// #line 188 "asm.yy"


void scanner_init()
{
    vec_init(strdupped, sizeof(char*));
}

void asm_src_buffer_push(struct membuf *buffer)
{
    if(src_buffer_depth == MAX_SRC_BUFFER_DEPTH)
    {
	fprintf(stderr, "source buffers nested too deep\n");
	exit(-1);
    }
    src_buffers[src_buffer_depth++] = YY_CURRENT_BUFFER;
    gtyy_scan_bytes(membuf_get(buffer), membuf_memlen(buffer));
}

static char *strdupped_get(char *text)
{
    char **pp;
    /*printf("get \"%s\" => ", text);*/
    if(vec_insert_uniq(strdupped, strdupped_cmp, &text, (void*)&pp))
    {
        /* replace the pointer to <text> since <text> will be reused */
        *pp = strdup(text);
    }
    /*printf("%p\n", *pp);*/
    return *pp;
}

static void strdupped_free(void *a)
{
    char *b = *(char**)a;
    /*printf("free => %p \"%s\"\n", b, b);*/
    free(b);
}

static int strdupped_cmp(const void *a, const void *b)
{
    char *c = *(char**)a;
    char *d = *(char**)b;

    return strcmp(c, d);
}

void scanner_free()
{
    vec_free(strdupped, strdupped_free);
}

void yycleanup()
{
  if (YY_CURRENT_BUFFER)
    gtyy_delete_buffer(YY_CURRENT_BUFFER);
  if (yy_start_stack)
  {
  	gtyy_flex_free(yy_start_stack);
  	yy_start_stack = 0;
  	yy_start_stack_ptr = 0;
  	yy_start_stack_depth = 0;
  }
}


